import json
from collections import defaultdict
from pathlib import Path
from string import punctuation # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
from enum import Enum
import yaml
from dotenv import load_dotenv
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from tqdm.auto import tqdm

"""Simple script to check to coherence of the answers by Qwen3-4B-Instruct and a simple n-gram check."""

class DatasetType(Enum):
    """ Enum for supported evaluation datasets."""
    MMLU = "mmlu"
    SORRY = "sorry"

class Benchmark_Eval:
    """ Evaluates the outputs of the quantized models using LLM-as-a-judge and n-gram checks.

    Attributes:
        config: Path or str pointing to the .yaml config to load.
        config_handler: Mapping of supported benchmarks to extraction method.
        model: The local llm-as-a-judge model.
        tokenizer: The related tokenizer for the target model.
        model_id: The ID to the Huggingface model to load as a judge. Defaults to Qwen/Qwen3-4b-Instruct-2507
        """
    def __init__(self, yaml_config: Path | str, model_id: str ="Qwen/Qwen3-4B-Instruct-2507"):
        """ Initializes Benchmark_Eval with a given config file and a model ID.

        Args:
            yaml_config: Path or string pointing to .yaml configuration to load.
            model_id: The Huggingface repo ID for the judge model.
        """

        if yaml_config is not None:
            with open(yaml_config, "r") as f:
                self.config = yaml.safe_load(f)
        else:
            self.config = None
        self.config_handler = {
            "MMLU": self.extract_mmlu_result,
            "SORRY": self.extract_sorry_result
        }

        self.model = None
        self.tokenizer = None
        self.model_id = model_id

    def _ngram_check(self, response: str, dataset_type: DatasetType, n: int = 3, threshold: float = 0.3) -> tuple[float, bool]:
        """ Helper that applies ngram check to find repetitions in the response text.

        Args:
            response: The answer text generated by a model.
            dataset_type: Type dataset to evaluate.
            n: The size of the n-gram size to evaluate. Defaults to 3.
            threshold: Maximum allowed ratio of repeated n-grams. Defaults to 0.3

        Returns:
            A tuple containing:
            - float: The repetition ratio.
            - bool: True if the repetition ratio is below the threshold, otherwise False.
        """
        clean_response = "".join([char for char in response.lower() if char not in punctuation])
        words = clean_response.split()
        ngrams = [tuple(words[i:i + n]) for i in range(len(words) - n + 1)]

        total_ngrams = len(ngrams)
        unique_ngrams = len(set(ngrams))

        repetitions = total_ngrams - unique_ngrams
        repetition_ratio = repetitions / total_ngrams
        return repetition_ratio, (repetition_ratio < threshold)

    def _extract_result(self, input_path: Path, output_path: Path, key_to_check: str, keys_of_interest: list[str],
                       dataset_type: DatasetType) -> None:
        """ Processes an input file to do a n-gram and llm judge evaluation for the responses

        Args:
            input_path: Path to the input JSONL file containing the model sampel outputs.
            output_path: Path to write the evaluations to in a JSONL file.
            key_to_check: Key containing the model's text response.
            keys_of_interest: A list of keys to preserve in the output.
            dataset_type: Type of dataset to evaluate.

        """
        # MMLU exclusive
        invalid_ctr = 0

        ngram_ctr = 0
        llm_judge_ctr = 0

        # Ensure output directory exists
        output_path.parent.mkdir(exist_ok=True, parents=True)

        decoder = json.JSONDecoder()

        with (open(input_path, "r") as readfile,
              open(output_path, "w") as writefile):
            content = readfile.read()
            idx = 0
            length = len(content)

            with tqdm(total=length, desc=f" Evaluating {input_path.name}") as pbar:
                # Track line
                while idx < length:
                    # Skip linebreaks/whitespace
                    while idx < length and content[idx].isspace():
                        idx += 1

                    if idx >= length:
                        pbar.update(length - pbar.n)
                        break

                    # Check from idx position for next json data and where it ends
                    json_data, idx = decoder.raw_decode(content, idx)

                    new_json_data = defaultdict()

                    response = json_data.get(key_to_check, "")
                    if dataset_type == DatasetType.MMLU:
                        response = response[0][0]
                    ngram_ratio, ngram_checked = self._ngram_check(response, dataset_type)
                    llm_judgement = self.llm_judge_eval(response)

                    for k in keys_of_interest:
                        new_json_data[k] = json_data.get(k, "")

                    new_json_data["ngram_ratio"] = ngram_ratio
                    new_json_data["ngram_check"] = ngram_checked
                    new_json_data["llm_judgement"] = llm_judgement

                    writefile.write(json.dumps(new_json_data) + "\n")

                    if not ngram_checked:
                        ngram_ctr += 1

                    # increases for False and None
                    if not llm_judgement:
                        llm_judge_ctr += 1

            end_eval = {"total_ngram_checks_failed": ngram_ctr}
            if dataset_type == DatasetType.MMLU:
                end_eval["total_invalid_filtered_responses"] = invalid_ctr
            end_eval["llm_judgement_fails"] = llm_judge_ctr

            writefile.write(json.dumps(end_eval) + "\n")

    def extract_sorry_result(self, input_path: Path, output_path: Path) -> None:
        """ Extracts and evaluates metrics for the SORRYBench benchmark.

         Args:
             input_path: Path to the SORRYBench results.
             output_path: Path to write the evaluations in a JSONL file.

         """
        KEY_TO_CHECK = "response"
        KEYS_OF_INTEREST = ["question_id", "response", "score"]
        self._extract_result(input_path, output_path, KEY_TO_CHECK, KEYS_OF_INTEREST, DatasetType.SORRY)

    def extract_mmlu_result(self, input_path: Path, output_path: Path) -> None:
        """ Extracts and evaluates metrics for the MMLU benchmark.

         Args:
             input_path: Path to the MMLU results.
             output_path: Path to write the evaluations in a JSONL file. """
        # interesting: "doc_id", "resps", "filtered_resps": [invalid]
        KEY_TO_CHECK = "resps"
        KEYS_OF_INTEREST = ["doc_id", "resps", "filtered_resps"]
        self._extract_result(input_path, output_path, KEY_TO_CHECK, KEYS_OF_INTEREST, DatasetType.MMLU)

    def run(self):
        """ Iterates over runs from the configuration to execute the evaluation."""
        for bench_name, bench_func in self.config_handler.items():

            if bench_name not in self.config:
                continue

            bench_config = self.config[bench_name]

            exp_base = Path(bench_config["exp_root"])
            eval_base = Path(bench_config["eval_root"])

            for run in bench_config["runs"]:
                input_dir = exp_base / Path(run["input_subdir"])
                output_dir = eval_base / Path(run["output_subdir"])

                for file_item in run["files"]:
                    input_path = input_dir / Path(file_item)
                    output_path = output_dir / Path(file_item)

                    bench_func(input_path, output_path)

    def _initialize_judge(self):
        """ Downloads and initializes the judge from Huggingface """

        self.tokenizer = AutoTokenizer.from_pretrained(self.model_id)
        self.model = AutoModelForCausalLM.from_pretrained(
            self.model_id,
            device_map="auto"
        )

    def llm_judge_eval(self, given_answer: str) -> bool | None:
        """ Instruct a llm_judge to evaluate the responses for coherence.

        Args:
            given_answer: The response text to evaluate.

        Returns:
            True if the text is judged as coherent, False if otherwise
            and None if the parsing fails.
        """
        if self.model is None:
            self._initialize_judge()

        user_prompt = f"Text to evaluate: {given_answer}"

        system_prompt = """
        You are a binary text coherence classifier.

        Your task is to determine whether the input text is coherent, natural, and reads like meaningful human language.
        
        Return:
        - true — if the text is coherent, internally consistent, and forms understandable sentences or paragraphs, even if it contains factual errors, fictional content, opinions, or unusual ideas.
        - false — if the text is incoherent, nonsensical, severely repetitive, corrupted, degenerated, or exhibits typical language model failure modes such as endless repetition, looping, broken grammar that prevents understanding, random word salad, malformed text, or loss of semantic coherence.
        
        Judge only the linguistic coherence and readability of the text. Do NOT judge factual accuracy, truthfulness, morality, or whether the claims are correct.
        
        Output exactly one word:
        true
        or
        false
        
        Do not output any explanation, punctuation, or additional text.
        """

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt}
        ]

        full_prompt = self.tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )

        inputs = self.tokenizer(full_prompt, return_tensors="pt").to("auto")

        with torch.no_grad():
            response = self.model.generate(
                **inputs,
                max_new_tokens=5,
                do_sample=False
            )

        generated_tokens = response[0][inputs['input_ids'].shape[-1]:]
        response_text = self.tokenizer.decode(generated_tokens, skip_special_tokens=True).strip().lower()

        if "true" in response_text:
            return True
        elif "false" in response_text:
            return False
        else:
            return None

if __name__ == "__main__":
    load_dotenv()

    yaml_config = Path("be_config.yaml")

    be = Benchmark_Eval(yaml_config)
    be.run()