from pathlib import Path
from typing import Any, Iterable
from contextlib import contextmanager
import sys
import logging
import json
import yaml

def load_yaml_config(path: str | Path) -> dict[str, Any]:
    """Loads and validation .yaml configuration file.

    Args:
        path: Shows to the .yaml configuration to load.

    Returns:
        A dictionary of the configuration and its keys. Returns an empty dictionary if the .yaml file is empty.

    Raises:
        ValueError: If the .yaml hierarchy does not match a dictionary.
    """

    path = Path(path)

    with path.open("r", encoding="utf-8") as f:

        data = yaml.safe_load(f)

    if data is None:

        return {}

    if not isinstance(data, dict):

        raise ValueError(f"Expected YAML top-level object to be a dict, got {type(data).__name__}")

    return data

def save_yaml_config(data: dict[str, Any], path: str | Path) -> Path:
    """Serializes a dictionary into a .yaml file destination.

    Args:
        data: The dictionary object of interest.
        path: The target output location.

    Returns:
        A Path object pointing to the written .yaml file.
    """

    path = Path(path)
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(data, f, sort_keys=False, allow_unicode=True)
    return path

def save_jsonl(records: Iterable[Any], path: str | Path) -> Path:
    """ Writes a requence of data records into a lines of JSON files.

    Args:
        records: An iterabile collection of to saved objects.
        path: The target save location.

    Returns:
        A Path object pointing to the written .jsonl file.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False, default=str, indent=4) + "\n")
    return path

def save_json(data: Any, path: str | Path) -> Path:
    """ Writes a sequence of data records into a standard JSON file.

    Args:
        data: The object to serialize.
        path: The target save location.

    Returns:
        A Path object pointing to the written .json file.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, default=str, indent=4)
    return path

# utilities to record command line output into a log

class _Tee:
    """ Writing and flushing across several streams at once.
    Utilized to logging concurrently.
    """
    def __init__(self, *streams):
        """ Initializes stream objects. """
        self._streams = streams

    def write(self, data) -> int:
        """ Writes data across all tracked streams.

        Args:
            data: Data block for logging.

        Returns:
            The length of the data object written to the stream.

        """
        for s in self._streams:
            s.write(data)
            s.flush()
        return len(data)

    def flush(self) -> None:
        """Flushes streams across all actively tracked streams. """
        for s in self._streams:
            s.flush()


@contextmanager
def tee_console(path: str | Path, mode: str = "w"):
    """
    Mirror everything printed to stdout/stderr (and logging) into `path`,
    while still showing it on the real console. Pass mode="a" to append
    (e.g. when resuming a run so the existing log is preserved).

    Args:
        path: Path pointing to the target log file.
        mode: Standard access codes. 'w' to overwrite file or 'a' to append.
            Defaults to 'w' for overwriting log file.

    Yields:
        A Path object directly pointing to the tracking log file.

    Generated by AI.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    f = path.open(mode, encoding="utf-8")

    old_out, old_err = sys.stdout, sys.stderr
    sys.stdout = _Tee(old_out, f)  # type: ignore[assignment]
    sys.stderr = _Tee(old_err, f)  # type: ignore[assignment]

    handler = logging.StreamHandler(f)
    handler.setLevel(logging.INFO)
    root = logging.getLogger()
    root.addHandler(handler)
    try:
        yield path
    finally:
        root.removeHandler(handler)
        sys.stdout, sys.stderr = old_out, old_err
        f.flush()
        f.close()


def collect_environment() -> dict[str, Any]:
    """Snapshot the machine meta data (OS / CPU / GPU) and key library versions so each
    experiment folder is self-describing for reproducibility.

    Returns:
        A nested dictionary tracking the following parameters:
        - timestamp: Execution time
        - platform: OS information and Python version
        - cpu: Processor model and core count
        - gpu: Graphic unit
        - libraries: Libraries used

    """
    import platform
    import os
    import subprocess
    from datetime import datetime
    from importlib.metadata import version, PackageNotFoundError

    def _safe(fn, default=None):
        try:
            return fn()
        except Exception:
            return default

    def _cpu_brand():
        system = platform.system()
        if system == "Darwin":
            return subprocess.check_output(
                ["sysctl", "-n", "machdep.cpu.brand_string"], text=True
            ).strip()
        if system == "Linux":
            with open("/proc/cpuinfo") as f:
                for line in f:
                    if line.startswith("model name"):
                        return line.split(":", 1)[1].strip()
        return platform.processor() or platform.machine()

    env: dict[str, Any] = {
        "timestamp": datetime.now().astimezone().isoformat(),
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "version": platform.version(),
            "machine": platform.machine(),
            "python": platform.python_version(),
            "node": platform.node(),
        },
        "cpu": {
            "brand": _safe(_cpu_brand),
            "count": os.cpu_count(),
        },
        "gpu": {},
        "libraries": {},
    }

    # Accelerator info via torch (best effort; torch is already imported by run time)
    try:
        import torch
        env["gpu"]["cuda_available"] = torch.cuda.is_available()
        if torch.cuda.is_available():
            env["gpu"]["cuda_version"] = torch.version.cuda
            env["gpu"]["devices"] = [
                torch.cuda.get_device_name(i) for i in range(torch.cuda.device_count())
            ]
        mps = getattr(torch.backends, "mps", None)
        env["gpu"]["mps_available"] = bool(mps and mps.is_available())
    except Exception as e:
        env["gpu"]["error"] = repr(e)

    for pkg in ["torch", "transformers", "bitsandbytes", "lm_eval", "accelerate", "numpy"]:
        try:
            env["libraries"][pkg] = version(pkg)
        except PackageNotFoundError:
            env["libraries"][pkg] = None

    return env


def seed_everything(seed: int):
    """ Sets the given seed across multiple libraries ( random, numpy, torch, torch.cuda)

    Args:
        seed: Randomized seed to set across libraries.
    """
    print(" >> Setting up randome seed", seed)
    import numpy as np
    import random
    import torch

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
